#!/bin/bash


# configure_ac_driver() - Copy the config file to the neutron path
function configure_ac_driver {
    cp $DIR_HUAWEI/etc/huawei_driver_config.ini.sample $NW_HUAWEI_AC_CONF_FILE
}

# ac_generate_config_files() - This API will be called for phase "post-config".
# It generates the sample config file with the default values
function ac_generate_config_files {
    (cd $DIR_HUAWEI && exec ./tools/generate_config_file_samples.sh)
}

# ac_post_configure() - Generate the use the config file for neutron plugin
function ac_post_configure {
    ac_generate_config_files
    configure_ac_driver
}